# Configuration Base de données (Render)
spring.datasource.url=${DB_URL:jdbc:postgresql://dpg-d5usbnili9vc739rafc0-a.virginia-postgres.render.com/todo_db_gi24}
spring.datasource.username=${DB_USERNAME:todo_db_gi24_user}
spring.datasource.password=${DB_PASSWORD:bfyxq24WIVbG5vrUtI5TjvQGGlIhfeE7}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Configuration JSP
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
